import { useState, useEffect } from "react";
import { supabase } from "../../lib/supabase";
import { useToast } from "@/components/ui/use-toast";
import { FileText, Download, Send, CheckCircle2, Copy, ExternalLink, Loader2, RefreshCw, Pencil } from "lucide-react";
import QuoteEditorModal from "../../components/admin/QuoteEditorModal";
import ReceiptPreviewModal from "../../components/admin/ReceiptPreviewModal";
import jsPDF from "jspdf";

export default function ProposalsLibrary() {
  const { toast } = useToast();
  const [quotes, setQuotes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [resendingId, setResendingId] = useState<string | null>(null);
  const [sendingPdfId, setSendingPdfId] = useState<string | null>(null);
  const [editingQuote, setEditingQuote] = useState<any>(null);
  const [previewReceiptQuote, setPreviewReceiptQuote] = useState<any>(null);

  useEffect(() => {
    fetchQuotes();
  }, []);

  async function fetchQuotes() {
    setLoading(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    const { data, error } = await supabase
      .from('quotes')
      .select('*, client:clients(first_name, last_name, email, phone)')
      .eq('installer_id', user.id)
      .order('created_at', { ascending: false });

    if (!error && data) {
      setQuotes(data);
    }
    setLoading(false);
  }

  const handleCopyLink = (id: string) => {
    navigator.clipboard.writeText(`https://www.resinacademics.com/quote-live/${id}`);
    toast({ title: "Link Copied", description: "Quote link copied to clipboard!" });
  };

  const getQuotePdfFileName = (quote: any) => {
    const first = quote.client?.first_name || "Client";
    const last = quote.client?.last_name || "Quote";
    return `Quote_${first}_${last}_${quote.id.slice(0, 8)}.pdf`.replace(/[^a-z0-9_.-]/gi, "_");
  };

  const buildQuotePdf = (quote: any) => {
    const doc = new jsPDF();
    const brandName = quote.config?.brand_name || quote.installer_email?.split('@')[0]?.toUpperCase() || "Resin OS";
    const clientName = `${quote.client?.first_name || ""} ${quote.client?.last_name || ""}`.trim() || "Client";
    const serviceType = quote.config?.service_type || "Custom Project";
    const scope = quote.config?.project_description?.trim();
    const terms = quote.config?.legal_terms?.trim();
    const milestones = quote.config?.payment_schedule?.milestones || [
      { label: "Deposit", pct: quote.config?.deposit_pct || 50 },
      { label: "Balance Due on Completion", pct: 100 - (quote.config?.deposit_pct || 50) }
    ];
    const smartLink = `https://www.resinacademics.com/quote-live/${quote.id}`;

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 16;
    const contentWidth = pageWidth - (margin * 2);
    const accent = quote.config?.theme_color || "#78c8ff";
    const dark = "#08090b";
    const panel = "#f5f7fb";
    let y = 18;

    const hexToRgb = (hex: string) => {
      const cleaned = hex.replace("#", "");
      const value = cleaned.length === 3
        ? cleaned.split("").map((char) => char + char).join("")
        : cleaned.padEnd(6, "0").slice(0, 6);
      return {
        r: parseInt(value.slice(0, 2), 16),
        g: parseInt(value.slice(2, 4), 16),
        b: parseInt(value.slice(4, 6), 16)
      };
    };

    const setFill = (hex: string) => {
      const { r, g, b } = hexToRgb(hex);
      doc.setFillColor(r, g, b);
    };

    const setText = (hex: string) => {
      const { r, g, b } = hexToRgb(hex);
      doc.setTextColor(r, g, b);
    };

    const ensureSpace = (needed = 24) => {
      if (y + needed > pageHeight - 18) {
        doc.addPage();
        y = 18;
        drawPageFooter();
      }
    };

    const drawPageFooter = () => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      setText("#8b93a1");
      doc.text(`Generated by Resin OS | Quote ID: ${quote.id}`, margin, pageHeight - 9);
    };

    const addWrappedText = (text: string, x: number, startY: number, maxWidth = 180, lineHeight = 6) => {
      const lines = doc.splitTextToSize(text, maxWidth);
      lines.forEach((line: string) => {
        ensureSpace(10);
        doc.text(line, x, y);
        y += lineHeight;
      });
      return startY + lines.length * lineHeight;
    };

    const sectionTitle = (title: string) => {
      ensureSpace(18);
      y += 4;
      setText("#0f172a");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(title, margin, y);
      setFill(accent);
      doc.roundedRect(margin, y + 3, 24, 1.5, 0.75, 0.75, "F");
      y += 12;
    };

    setFill(dark);
    doc.roundedRect(8, 8, pageWidth - 16, 64, 5, 5, "F");

    setFill(accent);
    doc.roundedRect(margin, 18, 11, 11, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(0, 0, 0);
    doc.text("OS", margin + 2.5, 25.2);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.setTextColor(255, 255, 255);
    doc.text(brandName, margin + 16, 24);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(180, 188, 202);
    doc.text("Premium Project Proposal", margin + 16, 31);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(25);
    setText(accent);
    doc.text(`$${quote.total_amount?.toLocaleString() || "0"}`, margin, 54);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(180, 188, 202);
    doc.text("TOTAL INVESTMENT", margin, 61);

    const quoteDate = new Date(quote.created_at).toLocaleDateString();
    const rightX = pageWidth - margin - 58;
    setFill("#141820");
    doc.roundedRect(rightX, 18, 58, 36, 4, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setText(accent);
    doc.text("QUOTE DATE", rightX + 5, 28);
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(quoteDate, rightX + 5, 37);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(180, 188, 202);
    doc.text(`ID ${quote.id.slice(0, 8).toUpperCase()}`, rightX + 5, 46);

    y = 86;

    setFill(panel);
    doc.roundedRect(margin, y, contentWidth, 42, 4, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    setText("#64748b");
    doc.text("PREPARED FOR", margin + 6, y + 10);
    setText("#0f172a");
    doc.setFontSize(15);
    doc.text(clientName, margin + 6, y + 20);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    setText("#475569");
    if (quote.client?.email) doc.text(quote.client.email, margin + 6, y + 28);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    setText("#64748b");
    doc.text("PROJECT TYPE", margin + 98, y + 10);
    setText("#0f172a");
    doc.setFontSize(11);
    const serviceLines = doc.splitTextToSize(serviceType, 78);
    doc.text(serviceLines.slice(0, 2), margin + 98, y + 20);
    y += 54;

    sectionTitle("Payment Schedule");
    setFill("#0f172a");
    doc.roundedRect(margin, y, contentWidth, 11, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text("MILESTONE", margin + 5, y + 7);
    doc.text("PERCENT", pageWidth - margin - 58, y + 7);
    doc.text("AMOUNT", pageWidth - margin - 26, y + 7);
    y += 13;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    milestones.forEach((milestone: any, index: number) => {
      ensureSpace(12);
      const amount = (quote.total_amount || 0) * ((milestone.pct || 0) / 100);
      if (index % 2 === 0) {
        setFill("#f8fafc");
        doc.roundedRect(margin, y - 5, contentWidth, 9, 2, 2, "F");
      }
      setText("#0f172a");
      doc.text(String(milestone.label || "Payment"), margin + 5, y);
      setText("#475569");
      doc.text(`${milestone.pct || 0}%`, pageWidth - margin - 55, y);
      doc.setFont("helvetica", "bold");
      setText("#0f172a");
      doc.text(`$${amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, pageWidth - margin - 27, y, { align: "left" });
      doc.setFont("helvetica", "normal");
      y += 10;
    });
    y += 4;

    if (scope) {
      sectionTitle("Scope of Work");
      setFill("#f8fafc");
      doc.roundedRect(margin, y - 3, contentWidth, 8, 2, 2, "F");
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      setText("#1f2937");
      scope.split("\n").forEach((paragraph: string) => {
        const trimmed = paragraph.trim();
        if (!trimmed) {
          y += 4;
          return;
        }
        addWrappedText(trimmed, margin + 5, y, contentWidth - 10, 5.8);
        y += 4;
      });
    }

    doc.setFont("helvetica", "bold");
    if (quote.config?.contract_pdf_url) {
      sectionTitle("Contract Note");
      setFill("#eef6ff");
      doc.roundedRect(margin, y - 3, contentWidth, 22, 3, 3, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      setText("#334155");
      addWrappedText("A custom contract PDF is attached to the smart proposal. If your firewall blocks the smart link, reply to this email and request the original contract PDF directly.", margin + 5, y + 4, contentWidth - 10, 5);
    } else if (terms) {
      sectionTitle("Contract Terms");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      setText("#334155");
      terms.split("\n").filter(Boolean).forEach((term: string) => {
        addWrappedText(`- ${term}`, margin + 2, y, contentWidth - 4, 5);
      });
      y += 4;
    }

    sectionTitle("Interactive Smart Proposal");
    setFill(dark);
    doc.roundedRect(margin, y - 4, contentWidth, 27, 4, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text("View, sign, and pay securely online when your network allows it:", margin + 6, y + 4);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    setText(accent);
    doc.text(smartLink, margin + 6, y + 13);

    drawPageFooter();

    return doc;
  };

  const handleDownloadQuotePdf = (quote: any) => {
    const doc = buildQuotePdf(quote);
    doc.save(getQuotePdfFileName(quote));
  };

  const handleSendQuotePdf = async (quote: any) => {
    const clientEmail = quote.client?.email?.trim();
    if (!clientEmail) {
      toast({
        title: "Client email missing",
        description: "Add an email to this client before sending a PDF.",
        variant: "destructive"
      });
      return;
    }

    setSendingPdfId(quote.id);
    try {
      const brandName = quote.config?.brand_name || quote.installer_email?.split('@')[0]?.toUpperCase() || "Resin OS";
      const smartLink = `https://www.resinacademics.com/quote-live/${quote.id}`;
      const doc = buildQuotePdf(quote);
      const pdfBase64 = doc.output("datauristring").split(",")[1];

      const res = await fetch('/api/send-email', {
        method: "POST",
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: clientEmail,
          cc: quote.installer_email,
          subject: `PDF Copy: Your Quote from ${brandName}`,
          html: `<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <div style="max-width:600px;margin:0 auto;background:#ffffff;padding:32px;border-radius:12px;">
    <h1 style="margin:0 0 12px;color:#111827;font-size:24px;">PDF Quote Attached</h1>
    <p style="color:#334155;font-size:16px;line-height:1.6;">Hi ${quote.client?.first_name || "there"},</p>
    <p style="color:#334155;font-size:16px;line-height:1.6;">I attached a PDF copy of your quote in case your company firewall blocks the interactive smart proposal.</p>
    <p style="color:#334155;font-size:16px;line-height:1.6;">If your network allows it later, the interactive version is still available here:</p>
    <p><a href="${smartLink}" style="color:#2563eb;font-weight:700;">View Interactive Smart Quote</a></p>
    <p style="color:#64748b;font-size:13px;margin-top:28px;">Sent via Resin OS.</p>
  </div>
</body>
</html>`,
          attachments: [
            {
              filename: getQuotePdfFileName(quote),
              content: pdfBase64
            }
          ]
        })
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => null);
        throw new Error(errorData?.error || "The email service rejected this PDF email.");
      }

      toast({ title: "PDF Quote Sent", description: `Emailed PDF copy to ${clientEmail}` });
    } catch (e: any) {
      toast({ title: "Error sending PDF", description: e.message || "Could not send the PDF quote.", variant: "destructive" });
    }
    setSendingPdfId(null);
  };

  const handleResend = async (quote: any) => {
    const clientEmail = quote.client?.email?.trim();
    if (!clientEmail) {
      toast({
        title: "Client email missing",
        description: "Add an email to this client before sending a reminder.",
        variant: "destructive"
      });
      return;
    }

    setResendingId(quote.id);
    try {
      const isFinal = quote.status === 'Won';
      const brandName = quote.config?.brand_name || quote.installer_email?.split('@')[0].toUpperCase() || 'us';
      const logoUrl = quote.config?.logo_url || '';
      
      const subject = isFinal ? `Final Invoice from ${brandName}` : `Reminder: Your Custom Quote from ${brandName}`;
      const headerTitle = isFinal ? 'Final Balance Due' : 'Following Up On Your Quote';
      const totalText = isFinal ? 'Remaining Balance' : 'Project Total';
      const amountValue = isFinal ? (quote.total_amount * 0.5) : quote.total_amount;
      
      const bodyText = isFinal 
        ? `Hello ${quote.client?.first_name || 'there'},<br><br>Thank you so much for your business! Your installation is complete and the final balance is now due. You can securely pay the remaining balance using the original encrypted link below.`
        : `Hello ${quote.client?.first_name || 'there'},<br><br>Just floating this back to the top of your inbox. Let us know if you have any questions about the proposal!`;
        
      const btnText = isFinal ? 'View & Pay Invoice' : 'View & Sign Secure Proposal';
      
      const res = await fetch('/api/send-email', {
        method: "POST",
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            to: clientEmail,
            cc: quote.installer_email,
            subject: subject,
            html: `<!DOCTYPE html>
<html>
<body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background-color: #f4f4f5; padding: 40px 0;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="max-width: 600px; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.05);">
          <tr>
            <td style="padding: 40px 40px 20px 40px; text-align: center;">
              ${logoUrl ? '<img src="' + logoUrl + '" alt="' + brandName + '" style="max-height: 60px; border-radius: 8px; margin-bottom: 20px;" />' : ''}
              <h1 style="margin: 0; font-size: 24px; color: #111827; letter-spacing: -0.5px;">${headerTitle}</h1>
            </td>
          </tr>
          <tr>
            <td style="padding: 0 40px 20px 40px;">
              <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px; text-align: center;">
                <p style="margin: 0; font-size: 12px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 1px;">${totalText}</p>
                <p style="margin: 8px 0 0 0; font-size: 32px; font-weight: 700; color: #3b82f6;">$${amountValue?.toLocaleString()}</p>
                <p style="margin: 8px 0 0 0; font-size: 14px; color: #94a3b8;">${quote.config?.service_type || 'Premium System'}</p>
              </div>
            </td>
          </tr>
          <tr>
            <td style="padding: 0 40px 30px 40px;">
              <p style="margin: 0 0 16px 0; font-size: 16px; line-height: 24px; color: #334155;">
                ${bodyText}
              </p>
              <table width="100%" cellpadding="0" cellspacing="0" role="presentation">
                <tr>
                  <td align="center" style="padding-top: 20px;">
                    <a href="https://www.resinacademics.com/quote-live/${quote.id}" style="display: inline-block; padding: 14px 32px; background-color: #111827; color: #ffffff; font-size: 16px; font-weight: 600; text-decoration: none; border-radius: 6px;">${btnText}</a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
        })
      });
      
      if (res.ok) {
        toast({ title: isFinal ? "Invoice Sent" : "Reminder Sent", description: `Emailed to ${clientEmail}` });
      } else {
        const errorData = await res.json().catch(() => null);
        toast({
          title: "Error sending email",
          description: errorData?.error || "The email service rejected this request.",
          variant: "destructive"
        });
      }
    } catch (e: any) {
      toast({ title: "Network Error", description: e.message || "Could not reach the email service.", variant: "destructive" });
    }
    setResendingId(null);
  };

  const handleSendReceipt = (quote: any) => {
    setPreviewReceiptQuote(quote);
  };

  const getStatusColor = (status: string) => {
    switch(status?.toLowerCase()) {
      case 'paid in full': return 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20';
      case 'paid': return 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20';
      case 'won': return 'text-emerald-400 bg-emerald-400/10 border-emerald-400/20';
      case 'opened': return 'text-blue-400 bg-blue-500/10 border-blue-500/30';
      case 'sent': return 'text-purple-400 bg-purple-400/10 border-purple-400/20';
      default: return 'text-zinc-400 bg-zinc-400/10 border-zinc-400/20'; // Draft
    }
  };

  return (
    <div className="min-h-screen bg-[#050505] p-6 lg:p-12 font-inter text-white">
      <div className="max-w-6xl mx-auto space-y-8">
        
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 border-b border-white/10 pb-6">
          <div>
            <h1 className="text-3xl font-space font-bold tracking-tight mb-2">Proposals Vault</h1>
            <p className="text-white/50 text-sm">Manage all sent quotes, track read receipts, and collect final payments.</p>
          </div>
          <button onClick={fetchQuotes} className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl hover:bg-blue-500/10 transition">
            <RefreshCw size={16} /> Refresh Data
          </button>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20 text-white/50">
            <Loader2 className="animate-spin mr-2" /> Loading Vault...
          </div>
        ) : quotes.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 bg-[#111] border border-white/5 rounded-2xl">
            <FileText size={48} className="text-white/20 mb-4" />
            <p className="text-white/60">No proposals generated yet.</p>
          </div>
        ) : (
          <div className="grid gap-4">
            {quotes.map((quote) => (
              <div key={quote.id} className="bg-[#111] border border-white/10 rounded-2xl p-6 hover:border-blue-500/30 transition-colors flex flex-col lg:flex-row gap-6 justify-between items-start lg:items-center">
                {(() => {
                  const clientEmail = quote.client?.email?.trim();
                  const canSendEmail = Boolean(clientEmail);
                  return (
                    <>
                
                {/* Client & Date */}
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-3">
                    <h3 className="text-xl font-bold">{quote.client?.first_name} {quote.client?.last_name || 'Client'}</h3>
                    <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider border ${getStatusColor(quote.status)}`}>
                      {quote.status || 'Draft'}
                    </span>
                  </div>
                  <p className={`text-sm font-mono truncate ${clientEmail ? 'text-white/50' : 'text-amber-300'}`}>
                    {clientEmail || 'No client email on file'}
                  </p>
                  <p className="text-white/30 text-xs">Created: {new Date(quote.created_at).toLocaleDateString()}</p>
                </div>

                {/* Money & Read Receipts */}
                <div className="flex-1 lg:text-center space-y-1">
                  <p className="text-2xl font-space font-bold text-[#ffffff]">${quote.total_amount?.toLocaleString()}</p>
                  {quote.config?.opened_at && quote.status !== 'Won' && quote.status !== 'Paid In Full' && (
                    <p className="text-xs text-blue-400 font-mono tracking-tight">
                      Last Viewed: {new Date(quote.config.opened_at).toLocaleDateString()}
                    </p>
                  )}
                  {quote.status === 'Won' && (
                    <p className="text-xs text-emerald-400 font-mono tracking-tight flex items-center justify-center lg:justify-center gap-1">
                      <CheckCircle2 size={12}/> Deposit Cleared
                    </p>
                  )}
                  {(quote.status === 'Paid In Full' || quote.status === 'Paid') && (
                    <p className="text-xs text-emerald-400 font-mono tracking-tight flex items-center justify-center lg:justify-center gap-1">
                      <CheckCircle2 size={12}/> Invoice Closed
                    </p>
                  )}
                </div>

                {/* Action Buttons */}
                <div className="flex items-center gap-2 w-full lg:w-auto">
                  <button onClick={() => handleCopyLink(quote.id)} className="flex-1 lg:flex-none p-3 lg:px-4 bg-white/5 hover:bg-blue-500/10 rounded-xl flex items-center justify-center gap-2 border border-white/10 transition-colors" title="Copy Smart Link">
                    <Copy size={16} className="text-white/70" />
                  </button>
                  
                  <a href={`/quote-live/${quote.id}`} target="_blank" rel="noreferrer" className="flex-1 lg:flex-none p-3 lg:px-4 bg-white/5 hover:bg-blue-500/10 rounded-xl flex items-center justify-center gap-2 border border-white/10 transition-colors" title="View Secure Document">
                    <ExternalLink size={16} className="text-[#ffffff]" />
                  </a>

                  <button onClick={() => handleDownloadQuotePdf(quote)} className="flex-1 lg:flex-none p-3 lg:px-4 bg-white/5 hover:bg-blue-500/10 rounded-xl flex items-center justify-center gap-2 border border-white/10 transition-colors" title="Download PDF Copy">
                    <Download size={16} className="text-white/70" />
                    <span className="sr-only">Download PDF</span>
                  </button>

                  <button
                    onClick={() => handleSendQuotePdf(quote)}
                    disabled={sendingPdfId === quote.id || !canSendEmail}
                    className="flex-1 lg:flex-none p-3 lg:px-4 bg-white/5 hover:bg-blue-500/10 rounded-xl flex items-center justify-center gap-2 border border-white/10 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    title={canSendEmail ? "Email PDF Copy" : "Add a client email first"}
                  >
                    {sendingPdfId === quote.id ? <Loader2 size={16} className="animate-spin text-white/70" /> : <FileText size={16} className="text-white/70" />}
                    <span className="sr-only">Email PDF</span>
                  </button>

                  {quote.status === 'Won' || quote.status === 'Paid' ? (
                    <>
                      <button onClick={() => handleResend(quote)} disabled={resendingId === quote.id || !canSendEmail} className="flex flex-1 lg:flex-none items-center justify-center gap-2 px-5 py-3 bg-emerald-500 hover:bg-emerald-600 text-white font-bold rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed" title={canSendEmail ? "Send invoice balance" : "Add a client email first"}>
                        {resendingId === quote.id ? <Loader2 size={16} className="animate-spin" /> : <><Send size={16} /> Invoice Balance</>}
                      </button>
                      <button onClick={() => handleSendReceipt(quote)} className="flex flex-1 lg:flex-none items-center justify-center gap-2 px-5 py-3 bg-[#78c8ff]/10 hover:bg-[#78c8ff]/20 text-[#78c8ff] font-bold rounded-xl border border-[#78c8ff]/20 transition-colors">
                        <FileText size={16} /> Build Receipt
                      </button>
                      {quote.config?.digital_footprint_pdf && (
                        <a href={`data:application/pdf;base64,${quote.config.digital_footprint_pdf}`} download={`Contract_${quote.client?.last_name || 'Executed'}.pdf`} className="flex-1 lg:flex-none p-3 lg:px-4 bg-[#ffffff]/10 hover:bg-[#ffffff]/20 text-[#ffffff] rounded-xl flex items-center justify-center gap-2 border border-[#ffffff]/30 transition-colors">
                          <Download size={16} />
                        </a>
                      )}
                    </>
                  ) : quote.status === 'Paid In Full' ? (
                    <>
                      <button onClick={() => handleSendReceipt(quote)} className="flex flex-1 lg:flex-none items-center justify-center gap-2 px-5 py-3 bg-[#78c8ff]/10 hover:bg-[#78c8ff]/20 text-[#78c8ff] font-bold rounded-xl border border-[#78c8ff]/20 transition-colors">
                        <FileText size={16} /> Build Receipt
                      </button>
                      {quote.config?.digital_footprint_pdf && (
                        <a href={`data:application/pdf;base64,${quote.config.digital_footprint_pdf}`} download={`Contract_${quote.client?.last_name || 'Executed'}.pdf`} className="flex flex-1 lg:flex-none items-center justify-center gap-2 px-8 py-3 bg-zinc-800 text-white font-bold rounded-xl hover:bg-zinc-700 transition-colors">
                          <Download size={16} /> Receipt PDF
                        </a>
                      )}
                    </>
                  ) : (
                    <>
                      <button onClick={() => setEditingQuote(quote)} className="flex flex-1 lg:flex-none items-center justify-center gap-2 px-4 py-3 bg-[#78c8ff]/10 hover:bg-[#78c8ff]/20 text-[#78c8ff] font-bold rounded-xl border border-[#78c8ff]/20 transition-colors">
                        <Pencil size={16} /> Edit & Re-send
                      </button>
                      <button onClick={() => handleResend(quote)} disabled={resendingId === quote.id || !canSendEmail} className="flex flex-1 lg:flex-none items-center justify-center gap-2 px-5 py-3 bg-white text-black font-bold rounded-xl hover:bg-gray-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed" title={canSendEmail ? "Send reminder" : "Add a client email first"}>
                        {resendingId === quote.id ? <Loader2 size={16} className="animate-spin" /> : <><Send size={16} /> Remind</>}
                      </button>
                    </>
                  )}
                </div>

                    </>
                  );
                })()}
              </div>
            ))}
          </div>
        )}

      </div>

      {editingQuote && (
        <QuoteEditorModal 
          quote={editingQuote} 
          onClose={() => setEditingQuote(null)} 
          onUpdate={fetchQuotes} 
        />
      )}
      
      {previewReceiptQuote && (
        <ReceiptPreviewModal 
          quote={previewReceiptQuote} 
          client={previewReceiptQuote.client}
          onClose={() => setPreviewReceiptQuote(null)}
        />
      )}
    </div>
  );
}
